apiVersion: apps/v1
kind: Deployment
metadata:
  name: html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
        - name: html
          image: gaeng02/docker_with_html:1.1.1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: html
spec:
  selector:
    app: html
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: gaeng02/docker_with_database:1.1.1
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: NodePort
